# Generated by Django 5.0.1 on 2024-03-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_homeurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('interested', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('available_slot', models.DateField()),
                ('time_availability', models.TimeField()),
                ('home_url', models.URLField()),
            ],
        ),
    ]
