# Generated by Django 5.0.1 on 2024-03-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='available_slot',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='home_url',
            new_name='Home_url',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='interested',
            new_name='Interested',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time_availability',
            new_name='Time',
        ),
    ]
