# Generated by Django 5.0.1 on 2024-03-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_available_slot_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='mobile_no',
            new_name='Mobile_no',
        ),
    ]
