# Generated by Django 5.0.1 on 2024-03-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_mobile_no_appointment_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
