# Generated by Django 5.0.1 on 2024-03-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_appointment_email_alter_appointment_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Mobile_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
