# Generated by Django 5.0.1 on 2024-04-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_appointment_email_alter_appointment_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
